// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VMentory.Core.Persistence;

#nullable disable

namespace VMentory.Core.Migrations
{
    [DbContext(typeof(VMentoryDbContext))]
    [Migration("20261002122103_AddRemoveSource")]
    partial class AddRemoveSource
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("VMentory.Core.Persistence.ActionDependencyEntity", b =>
                {
                    b.Property<string>("BlockedId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BlockerId")
                        .HasColumnType("TEXT");

                    b.HasKey("BlockedId", "BlockerId");

                    b.HasIndex("BlockerId");

                    b.ToTable("ActionDependencies");
                });

            modelBuilder.Entity("VMentory.Core.Persistence.ActionItemEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AffectedMachinesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AffectedVmsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("DoneWhen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .HasColumnType("TEXT");

                    b.Property<string>("How")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastDetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PurchasesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ref")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequiresDowntime")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ScheduledEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ScheduledStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Why")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ref")
                        .IsUnique();

                    b.HasIndex("SourceKey");

                    b.HasIndex("Status");

                    b.ToTable("Actions");
                });

            modelBuilder.Entity("VMentory.Core.Persistence.ActionNoteEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("TEXT");

                    b.Property<string>("By")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.ToTable("ActionNotes");
                });

            modelBuilder.Entity("VMentory.Core.Persistence.AppUserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VMentory.Core.Persistence.AuditEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Allowed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<string>("Verb")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp", "Username");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("VMentory.Core.Persistence.DekEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DekNonce")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WrappedDek")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Deks");
                });

            modelBuilder.Entity("VMentory.Core.Persistence.DrainPlanEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AbortRequested")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaintenanceReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("MaintenanceUntil")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReverseOfPlanId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceHostId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceNode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DrainPlans");
                });

            modelBuilder.Entity("VMentory.Core.Persistence.FleetRuleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MembersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FleetRules");
                });

            modelBuilder.Entity("VMentory.Core.Persistence.HardwareSnapshotEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ok")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("TakenAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TakenAt");

                    b.ToTable("HardwareSnapshots");
                });

            modelBuilder.Entity("VMentory.Core.Persistence.HostRegistrationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SkipTlsVerification")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseGlobalCreds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Hosts");
                });

            modelBuilder.Entity("VMentory.Core.Persistence.InventorySnapshotEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HostId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("TakenAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HostId", "TakenAt");

                    b.ToTable("Snapshots");
                });

            modelBuilder.Entity("VMentory.Core.Persistence.MachineEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ManagementIp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceTag")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StaticVmsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StaticVmsSource")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StaticVmsVerifiedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("Address");

                    b.HasIndex("ServiceTag");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("VMentory.Core.Persistence.MigrationJobEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long?>("BytesDone")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BytesPlanned")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CancelRequested")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CleanupDone")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("DrainPlanId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ForceStopOnTimeout")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GuestType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LogTail")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("PartialOnTarget")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phase")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanNote")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreflightJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("QueuedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RemoveSourceOnSuccess")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RowAction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Seq")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceHostId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceNode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SourceRestarted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetHostId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetNode")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetStorage")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TargetVmid")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TargetVmidWasFree")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("TransferEndedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("TransferStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Upid")
                        .HasColumnType("TEXT");

                    b.Property<int>("Vmid")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WasRunning")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DrainPlanId");

                    b.HasIndex("Status");

                    b.ToTable("MigrationJobs");
                });

            modelBuilder.Entity("VMentory.Core.Persistence.NodeMaintenanceEntity", b =>
                {
                    b.Property<string>("HostId")
                        .HasColumnType("TEXT");

                    b.Property<string>("By")
                        .HasColumnType("TEXT");

                    b.Property<string>("DrainPlanId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Since")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Until")
                        .HasColumnType("TEXT");

                    b.HasKey("HostId");

                    b.ToTable("NodeMaintenance");
                });

            modelBuilder.Entity("VMentory.Core.Persistence.SecretEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ciphertext")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nonce")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Secrets");
                });

            modelBuilder.Entity("VMentory.Core.Persistence.ActionDependencyEntity", b =>
                {
                    b.HasOne("VMentory.Core.Persistence.ActionItemEntity", "Blocked")
                        .WithMany("BlockedBy")
                        .HasForeignKey("BlockedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VMentory.Core.Persistence.ActionItemEntity", "Blocker")
                        .WithMany("Blocks")
                        .HasForeignKey("BlockerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blocked");

                    b.Navigation("Blocker");
                });

            modelBuilder.Entity("VMentory.Core.Persistence.ActionNoteEntity", b =>
                {
                    b.HasOne("VMentory.Core.Persistence.ActionItemEntity", "Action")
                        .WithMany("Notes")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");
                });

            modelBuilder.Entity("VMentory.Core.Persistence.InventorySnapshotEntity", b =>
                {
                    b.HasOne("VMentory.Core.Persistence.HostRegistrationEntity", "Host")
                        .WithMany("Snapshots")
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Host");
                });

            modelBuilder.Entity("VMentory.Core.Persistence.ActionItemEntity", b =>
                {
                    b.Navigation("BlockedBy");

                    b.Navigation("Blocks");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("VMentory.Core.Persistence.HostRegistrationEntity", b =>
                {
                    b.Navigation("Snapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
